name: Convert Resume to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: ${{ github.workspace }}/pdfs
          build_html: false
      - name: Move PDF to artifacts
        run: mv ${{ github.workspace }}/pdfs/*.pdf ${{ github.workspace }}/artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Resume PDF
          path: ${{ github.workspace }}/artifacts/
